site_name: passion


theme:
  name: "material"
  language: zh
  features:
    - navigation.tabs
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

plugins:
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          paths: [ passion ]

nav:
  - Index: index.md
  - API Documentation:
      - passion:
          - http: api/http.md
          - crypt: api/crypt.md
  - Reference: reference.md


markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
